### ISSUE TITLE
NullPointerException in BitbucketRepository.isFilteredBuild when bitbucket user account is deleted

### ISSUE THREAD

**Issue by mattwwarren** [nishio-dens/bitbucket-pullrequest-builder-plugin#124]
We had a former employee delete their user account, which had created some outstanding branches/PRs and then our builds were failing to start with the following exception.

```
java.lang.NullPointerException
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isFilteredBuild(BitbucketRepository.java:325)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isBuildTarget(BitbucketRepository.java:228)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:97)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
        at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:292)
        at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
        at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
        at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

I resolved the issue temporarily by making the following change.

```
diff --git a/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java b/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java
index 3b0a314..175b187 100644
--- a/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java
+++ b/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java
@@ -300,6 +303,7 @@ public class BitbucketRepository {
         // * see: https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/119
         // * see: https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/issues/98
         final String destinationCommitHash;
+        final String prAuthor;
         if (pullRequest.getDestination().getCommit() == null) {
             logger.log(Level.INFO, "Pull request #{0} ''{1}'' in repo ''{2}'' has a null value for destination commit.",
                     new Object[]{pullRequestId, pullRequestTitle, destinationRepoName});
@@ -308,6 +312,12 @@ public class BitbucketRepository {
             destinationCommitHash = pullRequest.getDestination().getCommit().getHash();
         }
 
+        if (pullRequest.getAuthor() != null){
+            prAuthor = pullRequest.getAuthor().getCombinedUsername();
+        } else {
+            prAuthor = "Deleted Account";
+        }
+
         BitbucketCause cause = new BitbucketCause(
           pullRequest.getSource().getBranch().getName(),
           pullRequest.getDestination().getBranch().getName(),
@@ -319,7 +329,7 @@ public class BitbucketRepository {
           pullRequestTitle,
           pullRequest.getSource().getCommit().getHash(),
           destinationCommitHash,
-          pullRequest.getAuthor().getCombinedUsername()
+          prAuthor
         );
         
         //@FIXME: Way to iterate over all available SCMSources
```

If this is an acceptable long-term fix, I am happy to make a PR to that effect. Forgive my crude java, it's been a few years.

**Comment by CodeMonk** [comment]
This is fixed in tip by our 1.0/2.0 conversion stuff. Please let me know if you are still seeing failures.
