### ISSUE TITLE
Failure authenticating with BASIC 

### ISSUE THREAD

**Issue by cbittencourt** [nishio-dens/bitbucket-pullrequest-builder-plugin#129]
We see the plugin successfully posting to Bitbucket PRs, but the logs have this for every job at the cron interval:
```
Sep 05, 2017 9:06:06 PM INFO org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
basic authentication scheme selected
Sep 05, 2017 9:06:06 PM INFO org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
Failure authenticating with BASIC 'Bitbucket.org HTTP'@bitbucket.org:443
Sep 05, 2017 9:06:06 PM WARNING bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient getAllValues
invalid response.
java.io.EOFException: No content to map to Object due to end of input
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2775)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:275)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getAllValues(ApiClient.java:206)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:292)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

The jobs I have using this plugin also do not have the username/password fields specified, but specifying those fields does not seem to change avoid these errors in the logs.

I looked through this plugin's source and noticed that the username/password fields are not being used when a credential is specified [BitbucketRepository.java:75](https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/blob/master/src/main/java/bitbucketpullrequestbuilder/bitbucketpullrequestbuilder/BitbucketRepository.java#L75)

Is this a known issue? I also looked through this repo's issues but didn't find anything related to this.

Thanks,
Carlos

**Comment by santus444** [comment]
Yeah, Have a same issue

`Nov 16, 2017 8:05:04 PM org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
INFO: basic authentication scheme selected
Nov 16, 2017 8:05:04 PM org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
INFO: Failure authenticating with BASIC 'Bitbucket.org HTTP'@bitbucket.org:443
Nov 16, 2017 8:05:04 PM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient getAllValues
WARNING: invalid response.
java.io.EOFException: No content to map to Object due to end of input
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2775)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:275)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getAllValues(ApiClient.java:206)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:292)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by wrvdklooster** [comment]
I have the same issue.

**Comment by ip1981** [comment]
Guys, you might want to have a look at a reworked fork of this plug-in - https://github.com/ip1981/bbprb, it supports web-hooks, and is much much smaller and cleaner. I made it because I need that very bad :)

**Comment by smrutimandal** [comment]
@ip1981 How do we add this plugin to Jenkins?

**Comment by ip1981** [comment]
Build with maven to get an hpi file, then upload, or copy, or pack into the Jenkins war. See https://wiki.jenkins.io/display/JENKINS/Plugin+tutorial

**Comment by smrutimandal** [comment]
@ip1981 Thanks. I will give it a try.

**Comment by joseph0x01** [comment]
@ip1981  I am trying your plugin,  I have successfully built the hpi and uploaded to Jenkins, triggered webhook from Bitbucket (pullrequest:updated) but no job is triggered, below is  my configuration:

(Tick) Bitbucket Pull Requests Builder
Credentials: None
Repository: <The name of the repository>
CI Identifier: <Arbitrary identifier>
CI Name: <Arbitrary name>


tail -f /var/log/jenkins/jenkins.log
No debugging message is shown when the hook is triggered (It is 200 as seen in bitbucket side)


The bitbucket webhook setup:
 http:// <IP>:8080/bitbucket-hook/

Trigger: When Pull request is updated / created


Please advise. Again thanks for the plugin.

**Comment by ip1981** [comment]
Enable more logging:

Add an option `-Djava.util.logging.config.file=/path/to/cfg`

Where `/path/to/cfg` looks like this:
```
org.jenkinsci.plugins.bbprb.BitbucketBuildListener.level = FINEST
org.jenkinsci.plugins.bbprb.BitbucketHookReceiver.level = FINEST
org.jenkinsci.plugins.bbprb.BitbucketBuildTrigger.level = FINEST
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
java.util.logging.ConsoleHandler.level = FINEST
```

**Comment by joseph0x01** [comment]
@ip1981 

Jan 26, 2018 8:34:12 AM WARNING org.jenkinsci.plugins.bbprb.BitbucketBuildTrigger start
Missing Bitbucket API credentials


I tried to add credentials (by clicking Add), but it is always "none"

**Comment by ip1981** [comment]
It should be Username/Password credentials. Checkout `credentials.xml` and job's `config.xml`.

Something like
```xml
        <com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
          <scope>GLOBAL</scope>
          <id>bitbucket-pwd</id>
          <description></description>
          <username>foo</username>
          <password>bar</password>
        </com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
```

And 
```xml
  <triggers>
    <org.jenkinsci.plugins.bbprb.BitbucketBuildTrigger plugin="bbprb@0.1.0">
      <spec></spec>
      <ciKey>jenkins</ciKey>
      <ciName>Jenkins</ciName>
      <credentialsId>bitbucket-pwd</credentialsId>
      <destinationRepository>org/repo</destinationRepository>
      <cancelOutdatedJobs>true</cancelOutdatedJobs>
      <checkDestinationCommit>false</checkDestinationCommit>
    </org.jenkinsci.plugins.bbprb.BitbucketBuildTrigger>
  </triggers>
```

**Comment by joseph0x01** [comment]
@ip1981 

Thank, The warning goes away now, but it is still not working. Below is the only log I have:

Augmented all extensions
Jan 26, 2018 9:02:53 AM INFO org.jenkinsci.plugins.bbprb.BitbucketBuildTrigger start
Creating Bitbucket API client
Jan 26, 2018 9:02:53 AM INFO jenkins.InitReactorRunner$1 onAttained
Loaded all jobs
Jan 26, 2018 9:02:53 AM INFO hudson.model.AsyncPeriodicWork$1 run
Started Download metadata
Jan 26, 2018 9:02:54 AM INFO hudson.model.AsyncPeriodicWork$1 run
Finished Download metadata. 147 ms
Jan 26, 2018 9:02:54 AM INFO jenkins.InitReactorRunner$1 onAttained
Completed initialization
Jan 26, 2018 9:02:54 AM INFO hudson.WebAppMain$3 run
Jenkins is fully up and running

**Comment by joseph0x01** [comment]
My bitbucket account has two factor authentication enabled,  will that cause any issue?

**Comment by ip1981** [comment]
> My bitbucket account has two factor authentication enabled, will that cause any issue?
I don't think so. I have 2FA enabled too, Bitbucket API is not protected with it (otherwise it would be useless).

What happens in Jenkins itself? Did you try to resend the BB notification after Jenkins is fully started?

**Comment by ip1981** [comment]
And maybe email me. I think we abuse this conversation. A little bit :)

**Comment by zanes2016** [comment]
I'm having the same issue. Is there not a simple patch to fix this and update this plugin?

Issue #137 is a duplicate
