### ISSUE TITLE
invalid response

### ISSUE THREAD

**Issue by lifeofguenter** [nishio-dens/bitbucket-pullrequest-builder-plugin#139]
```
Nov 23, 2017 9:25:00 PM WARNING bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient getAllValues
invalid response.
org.codehaus.jackson.JsonParseException: Unexpected character ('F' (code 70)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@20bdebde; line: 1, column: 2]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
	at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
	at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:275)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getAllValues(ApiClient.java:206)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:292)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lifeofguenter** [comment]
ok so this was due to "Forbidden" in the response body. Easy way to verify everything is setup:

```bash
$ curl --user 'httpuser:httppass' -i https://bitbucket.org/api/2.0/repositories/ORG/REPO/pullrequests/
```

**Comment by saisuprashanth** [comment]
Hi i am also having same issue,
run this command curl --user 'httpuser:httppass' -i https://bitbucket.org/api/2.0/repositories/ORG/REPO/pullrequests/

but could not solve this issue.

Jenkins Log
java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getAllValues(ApiClient.java:207)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.getPullRequests(ApiClient.java:105)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:292)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by CodeMonk** [comment]
@saisuprashanth Can you please provide a couple of log lines before that null pointer exception. It will probably contain a 429 response, iirc.
