### ISSUE TITLE
Comment on PR is triggering build on all open pull requests

### ISSUE THREAD

**Issue by guilhermejcgois** [nishio-dens/bitbucket-pullrequest-builder-plugin#182]
Hi, I have the follow configuration in my multibranch pipeline job:
```
bitbucketpr(projectPath:'git@bitbucket.org:${repositoryOwner}/${repositoryName}.git',
        credentialsId:'deployer',
        cron: '* * * * *',
        username: '',
        password: '',
        repositoryOwner: 'gi',
        repositoryName: 'g-c',
        branchesFilter: '',
        branchesFilterBySCMIncludes: false,
        ciKey: 'jenkins_build_g-c',
        ciName: 'jenkins_build',
        ciSkipPhrases: 'skip-ci',
        checkDestinationCommit: false,
        approveIfSuccess: false,
        cancelOutdatedJobs: true,
        commentTrigger: 'jenkins test this please')```

Am I doing something wrong? Or can be a bug? Also, I have this chckout:

```
stage('Checkout SCM') {
            steps {
                bat 'git config --system core.longpaths true'
                checkout scm
            }
        }
```

Trigger all PR isn't a real problem, but, I have PR 1 and PR 2. Commenting `jenkins test this please` on PR 1, will trigger build in both open PR. And only the second fail:

```
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
hudson.plugins.git.GitException: Command "git.exe rev-parse "52d94bb12773^{commit}"" returned status code 128:
stdout: 52d94bb12773^{commit}

stderr: fatal: ambiguous argument '52d94bb12773^{commit}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2016)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1984)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1980)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1612)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1624)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:809)
	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1070)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1187)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:120)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:90)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:77)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:50)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by guilhermejcgois** [comment]
@nishio-dens can u address this? Is that the expected behaviour?

**Comment by CodeMonk** [comment]
My checkout line for a PR based build is this:

`git branch: "${env.branch}", credentialsId: 'EID_STRING'', url: 'git@bitbucket.org:ACCOUNT/REPO`

**Comment by CodeMonk** [comment]
I have just merged several fixes. While I have not seen this particular issue, there were many bugs in the trigger code that were repaired, so, this *could* be fixed now.

I will be pushing a new official version today, so, hopefully, we'll have something shiny and new to play with by the end of the week.
