### ISSUE TITLE
Basic authentication does not work

### ISSUE THREAD

**Issue by jdrbc** [nishio-dens/bitbucket-pullrequest-builder-plugin#197]
I'm getting this error when using app password. Happens whether I fill the un/pw form fields for this plugin or select a Jenkins managed credential. Jenkins has a successfully connection to bitbucket with other plugins.

`SCM changes detected in [my-project-name] - STAGE 2019.05. Triggering  #77
Apr 05, 2019 12:03:08 PM INFO org.apache.commons.httpclient.auth.AuthChallengeProcessor selectAuthScheme
basic authentication scheme selected
Apr 05, 2019 12:03:08 PM INFO org.apache.commons.httpclient.HttpMethodDirector processWWWAuthChallenge
Failure authenticating with BASIC 'Bitbucket.org HTTP'@bitbucket.org:443
Apr 05, 2019 12:03:08 PM WARNING bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient send
Response status: HTTP/1.1 401 Unauthorized URI: https://bitbucket.org/my-company-name/my-project-core/rest/api/1.0/projects/my-company-name/repos/my-project-core/pull-requests/
Apr 05, 2019 12:03:08 PM WARNING bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient send
Apr 05, 2019 12:03:08 PM WARNING bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerApiClient getAllValues
invalid response.
java.lang.NullPointerException
	at java.io.StringReader.<init>(Unknown Source)
	at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:636)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1877)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.ApiClient.parse(ApiClient.java:211)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerApiClient.getAllValues(ServerApiClient.java:122)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.server.ServerApiClient.getPullRequests(ServerApiClient.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:117)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger$TriggerRunnable.run(BitbucketBuildTrigger.java:402)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

**Comment by tkhkokd** [comment]
This is still happening against Bitbucket Cloud.

**Comment by tkhkokd** [comment]
Switched to using Jenkins credentials, but does not work.
