### ISSUE TITLE
can't get the plugin working with pipeline

### ISSUE THREAD

**Issue by tonytvo** [nishio-dens/bitbucket-pullrequest-builder-plugin#205]
Hi, 

for some reason, I couldn't get the pipeline working with bitbucketpr, here's my pipeline

pipeline {
    agent any 

    triggers {
        bitbucketpr(projectPath:'',
            bitbucketServer:'https://git.xxx.com',
            cron:'* * * * *',
            credentialsId:'xxxx',
            username:'',
            password:'',
            repositoryOwner:'xxxOwner',
            repositoryName:'xxxRepository',
            branchesFilter:'s:r:^finr',
            branchesFilterBySCMIncludes:false,
            ciKey:'jenkins',
            ciName:'Jenkins',
            ciSkipPhrases:'',
            checkDestinationCommit:false,
            approveIfSuccess:true,
            cancelOutdatedJobs:true,
            commentTrigger:'test this please')
    }

    stages {
        stage('Build') { 
            steps {
                echo "build"
            }
        }
        stage('Test') { 
            steps {
                echo "Test" 
            }
        }
    }
}

Although it seems to work for me when I did it through freestyle jobs, is there any recommendation?

Also, how can I debug this on my jenkins?
one way I could see is to checkout this project, build it and upload the hci manually to my jenkins and test it out, is there any gotchas I need to watch out for?

**Comment by CodeMonk** [comment]
I've never tried pipeline like that. I have always configured the trigger via the GUI:

![Untitled](https://user-images.githubusercontent.com/130390/61474077-0bf5b380-a945-11e9-9052-57497281f608.png)

**Comment by ejrgilbert** [comment]
@CodeMonk What version of the plugin are you using? I'm on `1.4.30` and am unable to get it to work with a SCM'ed pipeline. I have the trigger configured through the GUI and use the Git portion of the Source Code Management config to set up the Git repository to pull from.

However, the `sourceBranch` and `targetBranch` variables are not defined.

**Comment by ejrgilbert** [comment]
After looking a bit more, it seems the `injectedEnvVars.txt` isn't getting generated in any of the builds. And the console output for the Jenkins jobs don't have the line `[EnvInject] - Loading node environment variables.` This would make sense for why the environment variables aren't getting defined.

So it seems that the `BitbucketAdditionalParameterEnvironmentContributor` isn't getting triggered for some reason for pipeline builds? Hopefully this helps a bit.

**Comment by CodeMonk** [comment]
Awesome - great find!

But, is there a way we could make things easier from the plugin side? Is
there a way to give Jenkins enough information to have `checkout scm`
simply work?

-Dave

**Comment by JasonDictos** [comment]
This seems related to an issue I posted today: #215

Any other way to get this to work then the above mentioned work around?

**Comment by CodeMonk** [comment]
That merge squash was fixed several weeks ago.

Are you still having issues?

**Comment by RayOei** [comment]
I seem to have the same issue.
Plugin version 1.5.0
As you can see this _is_ triggered by the PR. But the subsequent SCM definition for the "Pipeline script from SCM" doesn't recognize the environment variable.
The build.xml in the Jenkins job directory does contain the 'sourceBranch' variable as far as I can make out.

Any idea?

`<a href="https://bitbucket.org/xxxxx/xxxx/pull-request/43">#43 xx</a>
hudson.plugins.git.GitException: Command "git fetch --tags --progress --prune origin +refs/heads/${sourceBranch}:refs/remotes/origin/${sourceBranch}" returned status code 128:
stdout: 
stderr: fatal: Couldn't find remote ref refs/heads/${sourceBranch}
fatal: The remote end hung up unexpectedly

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2429)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2043)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:80)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:568)
	at jenkins.plugins.git.GitSCMFileSystem$BuilderImpl.build(GitSCMFileSystem.java:352)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:197)
	at jenkins.scm.api.SCMFileSystem.of(SCMFileSystem.java:173)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:115)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:69)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:299)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE`

**Comment by aetos382** [comment]
I have the same problem.
Plugin version 1.5.0

How should I set up the followings?

- Jenkins pipeline job configuration GUI
- trigger definition in Jenkinsfile
- checkout step in Jenkinsfile

**Comment by CodeMonk** [comment]
1. I use the gui and pipeline build
2. The trigger definition is identical to the documentation: builder configured with creds, and repo name and account set correctly. Then, I use a jenkinsfile from the SCM.
3. Finally, the checkout step I use in my Jenkinsfile is: `checkout scm`

There used to be issues with `checkout scm`, but, those were fixed in 1.5.0

**Comment by CodeMonk** [comment]
Keep in mind, you CANNOT click the rebuild button on a PR build. The branch information will not be present. You have to either push a new commit, rebase a new commit, or comment on the PR with the trigger phrase
