### ISSUE TITLE
java.lang.NullPointerException in getTargetPullRequests

### ISSUE THREAD

**Issue by allustin** [nishio-dens/bitbucket-pullrequest-builder-plugin#28]
In the Jenkins log i see 

``` java
bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run() failed for hudson.model.FreeStyleProject@4b292aae[1Script-Pull-Request-Build]
java.lang.NullPointerException
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:49)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:30)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:136)
    at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
    at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

Settings are checked:

![2014-12-03 01-48-50](https://cloud.githubusercontent.com/assets/55323/5272672/f8e3f9fc-7a8f-11e4-87c3-30856e8d26c7.png)

Repository use SSH connect like it describe in documentation

Jenkins version - 1.592, plugin - latest 1.4.1

**Comment by tkelley-eg** [comment]
This should be fixed with pull request #36 

https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/36

**Comment by klub** [comment]
Hi. I am having exactly the same error. I have an active pull request with comments on BItBucket but i get the same error in the logs. I am using version bbprbp 1.4.5 and jenkins version 1.617.


Under the GIT section of the job configuration page i have the following configuration:

Name: origin
Refspec: 
Branch Specifier (blank for 'any'): */${sourceBranch}

**Comment by dylanschoenmakers** [comment]
+1 I am having the same problems.

```
WARNING: bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run() failed for hudson.model.FreeStyleProject@2cb6749f[GewoonPien Bitbucket Pull Request]
java.lang.NullPointerException
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:55)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:30)
	at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:145)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:215)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by dylanschoenmakers** [comment]
Well I found out why it wasn't working in my case. The title of our repository is with capitals, but in the url and api it is all lower case.

So try specifying RepositoryName with all lowercase!

**Comment by BrettThePark** [comment]
Also had the case issue. Lowercase resolved

**Comment by tkhkokd** [comment]
This is still happening in 2020

**Comment by CodeMonk** [comment]
> This is still happening in 2020

No, it isn't.

Perhaps you're seeing another NullPointerException. Perhaps you're seeing similar behavior. But, you definitely aren't seeing the same behavior that existed in the code five years ago.

If you'd like someone to look at something, please file a NEW issue, with a description, logs, details, etc.

Saying "me too" in tickets closed two years ago, and last updated five years ago is not constructive in finding a solution.
