### ISSUE TITLE
Check for Pull Requests results in error

### ISSUE THREAD

**Issue by DoDoENT** [nishio-dens/bitbucket-pullrequest-builder-plugin#63]
How do you perform authentication? I've configured plugin to use username and password of user that uses two-factor authentication. Is that a problem? Do I have to configure something special on bitbucket repository?

It would be much easier if code from [this plugin](https://wiki.jenkins-ci.org/display/JENKINS/BitBucket+Plugin) would be reused to support triggering via BitBucket's webhooks.

Here is a log:

```
Oct 19 17:28:00 rambo jenkins[5798]: INFO: Fetch PullRequests.
Oct 19 17:28:02 rambo jenkins[5798]: Oct 19, 2015 5:28:02 PM bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.BitbucketApiClient getPullRequests
Oct 19 17:28:02 rambo jenkins[5798]: WARNING: invalid pull request response.
Oct 19 17:28:02 rambo jenkins[5798]: org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
Oct 19 17:28:02 rambo jenkins[5798]: at [Source: java.io.StringReader@364d50af; line: 1, column: 2]
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
Oct 19 17:28:02 rambo jenkins[5798]: at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1863)
Oct 19 17:28:02 rambo jenkins[5798]: at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.BitbucketApiClient.parsePullRequestJson(BitbucketApiClient.java:172)
Oct 19 17:28:02 rambo jenkins[5798]: at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.bitbucket.BitbucketApiClient.getPullRequests(BitbucketApiClient.java:42)
Oct 19 17:28:02 rambo jenkins[5798]: at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:53)
Oct 19 17:28:02 rambo jenkins[5798]: at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:30)
Oct 19 17:28:02 rambo jenkins[5798]: at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:153)
Oct 19 17:28:02 rambo jenkins[5798]: at hudson.triggers.Trigger.checkTriggers(Trigger.java:282)
Oct 19 17:28:02 rambo jenkins[5798]: at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
Oct 19 17:28:02 rambo jenkins[5798]: at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
Oct 19 17:28:02 rambo jenkins[5798]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
Oct 19 17:28:02 rambo jenkins[5798]: at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
Oct 19 17:28:02 rambo jenkins[5798]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
Oct 19 17:28:02 rambo jenkins[5798]: at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
Oct 19 17:28:02 rambo jenkins[5798]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Oct 19 17:28:02 rambo jenkins[5798]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Oct 19 17:28:02 rambo jenkins[5798]: at java.lang.Thread.run(Thread.java:745)
```

**Comment by DoDoENT** [comment]
OK, I can now confirm that two-factor authentication is a problem. I've tried with a user that does not have this feature enabled and plugin correctly triggered the build.

I'll leave that issue open until there is some kind of "support" for two-factor authentication, POST hook process or at least some documentation telling that users with enabled two-factor authentication are not supported.

**Comment by micheal-swiggs** [comment]
@DoDoENT Thanks for your comment, I had the same problem.
