### ISSUE TITLE
Plugin fails to inject environment variables possibly due to Jenkins Security Advisory 2016-05-11

### ISSUE THREAD

**Issue by robruma** [nishio-dens/bitbucket-pullrequest-builder-plugin#86]
Running jenkins-2.5-1.1 with Java 1.7.0_101

Console output from the build:
```
<a href="https://bitbucket.org/myuser/myrepo/pull-request/12">#12 my PR</a>
[EnvInject] - Loading node environment variables.
Building in workspace /var/lib/jenkins/workspace/myjob
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://bitbucket.org/${repositoryOwner}/${repositoryName}.git # timeout=10
Fetching upstream changes from https://bitbucket.org/${repositoryOwner}/${repositoryName}.git
 > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.username jenkins # timeout=10
 > git config --local credential.helper store --file=/tmp/git90023574673690410054.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://bitbucket.org/${repositoryOwner}/${repositoryName}.git +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://bitbucket.org/${repositoryOwner}/${repositoryName}.git
  at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:810)
  at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1066)
  at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1097)
  at hudson.scm.SCM.checkout(SCM.java:485)
  at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
  at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
  at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
  at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
  at hudson.model.Run.execute(Run.java:1741)
  at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
  at hudson.model.ResourceController.execute(ResourceController.java:98)
  at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://bitbucket.org/${repositoryOwner}/${repositoryName}.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: remote: Not Found
fatal: repository 'https://bitbucket.org/${repositoryOwner}/${repositoryName}.git/' not found

  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1719)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1463)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:63)
  at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:314)
  at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:808)
  ... 11 more
ERROR: null
Finished: FAILURE
```

See the following advisories:
https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2016-05-11
https://jenkins.io/blog/2016/05/11/security-update/
https://wiki.jenkins-ci.org/display/JENKINS/Plugins+affected+by+fix+for+SECURITY-170

**Comment by frodeaa** [comment]
Yes, the bug is caused by Jenkins Security Advisory 2016-05-11

**Workaround:**
set `hudson.model.ParametersAction.keepUndefinedParameters` to `true`

    java -Dhudson.model.ParametersAction.keepUndefinedParameters=true -jar jenkins.war

**Comment by saada** [comment]
Here's the fix implemented for the github plugin: https://github.com/jenkinsci/ghprb-plugin/pull/344
Maybe we can do the same for this plugin?

**Comment by houmie** [comment]
Any ETA when this fix will be released? The workaround doesn't work for us.

**Comment by saada** [comment]
@houmie, it looks like it's almost done: https://github.com/nishio-dens/bitbucket-pullrequest-builder-plugin/pull/88
