### ISSUE TITLE
Pull requests with merge conflicts cause crash

### ISSUE THREAD

**Issue by kennyk** [nishio-dens/bitbucket-pullrequest-builder-plugin#98]
The Exception is:

```
bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run() failed for
hudson.model.FreeStyleProject@67f06aa8[my-repo pull requests]
java.lang.NullPointerException
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isFilteredBuild(BitbucketRepository.java:287)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.isBuildTarget(BitbucketRepository.java:211)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketRepository.getTargetPullRequests(BitbucketRepository.java:94)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketPullRequestsBuilder.run(BitbucketPullRequestsBuilder.java:37)
    at bitbucketpullrequestbuilder.bitbucketpullrequestbuilder.BitbucketBuildTrigger.run(BitbucketBuildTrigger.java:187)
    at hudson.triggers.Trigger.checkTriggers(Trigger.java:272)
    at hudson.triggers.Trigger$Cron.doRun(Trigger.java:221)
    at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

It looks like this is caused by `GET /pullrequests` returning `null` in `destination.commit` when a pull request has a merge conflict:

```
...
"destination":{  
            "commit":null,
            "repository":{  
               "links":{  
                  "self":{  
                     "href":"https://bitbucket.org/!api/2.0/repositories/my-user/my-repo"
                  },
                  "html":{  
                     "href":"https://bitbucket.org/my-user/my-repo"
                  },
                  "avatar":{  
                     "href":"https://bitbucket.org/my-user/my-repo/avatar/32/"
                  }
               },
               "type":"repository",
               "name":"my-repo",
               "full_name":"my-user/my-repo",
               "uuid":"{084b808e-b7e1-40b0-84e6-8bd23e8114db}"
            },
        },
        "branch":{  
           "name":"dev"
        }
...
```

and so creating a `BitbucketCause` instance crashes on this line in `BitbucketRepository.isFilteredBuild()`:

``` java
pullRequest.getDestination().getCommit().getHash()
```

 taking the entire pull request fetching process with it. Meaning, not only is the pull request with the merge conflict not built, neither is any  other pull request.

**Comment by CodeMonk** [comment]
Looks like this was fixed a while ago
